### ISSUE TITLE
Question About Your Next.js WordPress Template

### ISSUE THREAD

**Issue by PaoloJN** [gregrickaby/gregrickaby#75]
Hey Greg,

I hope you're doing well! 😊

I recently came across your [Next.js WordPress template](https://github.com/gregrickaby/nextjs-wordpress), and I noticed that the repository mentions the your website is using the template. However, when I looked at the code, it seems like it's actually using the WordPress REST API instead. Just curious why the change? Was it for performance reasons or just convenience?

Thanks!

**Comment by gregrickaby** [comment]
@PaoloJN I'm doing well, thank you! 😄

Firstly, I appreciate your interest in the [Next.js WordPress repository](https://github.com/gregrickaby/nextjs-wordpress) and for taking the time to read the documentation. 😅

To address your question: with the upcoming releases of Next.js 15 and React 19, I wanted to experiment with those on my personal website rather than on a stable repository.

I haven't moved away from GraphQL entirely. Recently, I discovered that you can efficiently query the WordPress REST API using the [fields parameter](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields). Here's an example query:
```text
https://blog.gregrickaby.com/wp-json/wp/v2/posts?slug=sienna-by-starlight&_fields=id,date,slug,status,title,excerpt,content
```
I'm just experimenting at this stage, but so far, it appears to be significantly faster than GraphQL and doesn't require any plugins! I haven't tried to query comments yet, that's where GraphQL comes in handy.

Hope this helps answer your question! 🍻

**Comment by PaoloJN** [comment]
@gregrickaby Thanks for the info! 😊
